language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to run tests
install:
  - pip install coverage codacy-coverage
script:
  - coverage run -m unittest
  - coverage xml
  - python-codacy-coverage -r coverage.xml
