language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to run tests
install:
  - pip install coverage codacy-coverage
script:
  - coverage run -munittest xml
  - python-codacy-coverage -r coverage.xml